#pragma once

enum
{
	INSTRUCTION_NULL = 0,
	INSTRUCTION_GO,
	INSTRUCTION_SAY,
	INSTRUCTION_OPTION,
	INSTRUCTION_CONDITION,
	INSTRUCTION_EVALUATEFLAG,
	INSTRUCTION_NOT,
	INSTRUCTION_AND,
	INSTRUCTION_OR,
	INSTRUCTION_SETFLAG,
	INSTRUCTION_UNSETFLAG,
	INSTRUCTION_EVENT,
	INSTRUCTION_RETURN
};

enum
{
	// Events 0 .. n are 'use item' events where the event index references the item by index
	EVENT_ENTERROOM = 252,
	EVENT_EXITROOM,
	EVENT_NAMEATTRIBUTE,
	EVENT_DESCRIPTIONATTRIBUTE
};

